### ISSUE TITLE
Remove synchronizetion effect from Videos

### ISSUE THREAD

**Issue by ShadananaK** [CallToPower/Synchronize.js#10]
Hello  Denis Meyer,

Does Synchronize.js have any API to remove the effect of synchronizetion dynamically using javascript.

i.e **Reverse procedure of following command**  : 
$.synchronizeVideos(masterVideoNumber,mediagroup); 

I wanted to remove the synchronization effect between two videos after some time like when user click on some button.

Please help me....

**Comment by CallToPower** [comment]
I will have a look at this issue!

**Comment by ShadananaK** [comment]
Thank you very much ..I am waiting for your update....

**Comment by CallToPower** [comment]
@ShadananaK This issue should be resolved with version v1.2.4 [1], I added the event "sjs:unsynchronize".

[1] https://github.com/CallToPower/Synchronize.js/releases/tag/v1.2.4
