### ISSUE TITLE
Synchronizing between two master videos. 

### ISSUE THREAD

**Issue by ShadananaK** [CallToPower/Synchronize.js#9]
HI Denis Meyer,

First of all,thank you very much for sharing this wonderful  code, it is amazing!

Ok. coming to my issue.I will explain you in brief  -

I have two html5 videojs videos to be synchronized.which can be done from your code. But i want both videos to be act as Master.

i.e if i change the seek point in any one video(out of two) it should effect the other and vice versa.

How to achieve above task using your Synchronize.js.If you want some more information i can give you that Please help me...

Thank you

**Comment by CallToPower** [comment]
Hi ShadananaK,

Synchronize.js was designed to have one master and several slave videos, so it's not possible to have two master videos.

**Comment by ShadananaK** [comment]
oh ok. Thank you for information.

**Comment by masiorama** [comment]
@ShadananaK did you find a solution? I'm trying to achieve the same result :)
